#pragma once
#include <iostream>
#include <fmt/core.h>
#include <fmt/color.h>
#include <SFML/Graphics.hpp>
#include <vector>
#include <array>
#include <filesystem>
#include <cstdlib>
#include <algorithm>
#include <fstream>
#include <unordered_map>